title: "Harrison Deacon — Engineering Portfolio"
email: harrydeacon2004@gmail.com
description: >-
Mechanical/Mechatronics engineer focused on automation, controls, and prototyping.
url: "https://harry04d.github.io"
baseurl: ""
remote_theme: "mmistakes/minimal-mistakes@4.27.3"
minimal_mistakes_skin: "mint"
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: Sydney

include:
  - _pages

paginate: 5
paginate_path: "/blog/page:num/"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name: "Harrison Deacon"
  avatar: "/assets/images/avatar.jpg"
  bio: "Australian engineer — robotics, embedded, data."
  location: "Sydney, AU"
  links:
    - label: Email
      icon: "fas fa-fw fa-envelope"
      url: "harrydeacon2004@gmail.com"
    - label: LinkedIn
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/harrison-deacon-11a0ba210/"

# Collections
collections:
projects:
output: true
permalink: /projects/:name/

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
      author_profile: true
      toc: true
  - scope:
      path: ""
      type: "posts"
    values:
      layout: single
      author_profile: true
      toc: true
      read_time: true
      comments: false
  - scope:
      path: ""
      type: "projects"
      values:
      layout: single
      author_profile: true
      toc: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
